name = "echada"
description = "echo executable in ada"
version = "1.0"

authors = ["Tidian DELAGE"]
maintainers = ["Tidian DELAGE <tidian.delage@protonmail.ch>"]
maintainers-logins = ["PalsFreniers"]

executables = ["echada"]
